apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinywaffen-config-pvc
  labels:
    app: tinywaffen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinywaffen-data-pvc
  labels:
    app: tinywaffen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinywaffen-logs-pvc
  labels:
    app: tinywaffen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard