apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinywaffle-config-pvc
  labels:
    app: tinywaffle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinywaffle-data-pvc
  labels:
    app: tinywaffle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinywaffle-logs-pvc
  labels:
    app: tinywaffle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard