apiVersion: v1
kind: ServiceAccount
metadata:
  name: tinywaffen
  labels:
    app: tinywaffen

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tinywaffen
  labels:
    app: tinywaffen
rules:
- apiGroups: [""]
  resources: ["endpoints", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tinywaffen
  labels:
    app: tinywaffen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tinywaffen
subjects:
- kind: ServiceAccount
  name: tinywaffen
  namespace: default