apiVersion: v1
kind: Service
metadata:
  name: tinywaffle
  labels:
    app: tinywaffle
spec:
  selector:
    app: tinywaffle
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: admin
    port: 2019
    targetPort: 2019
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: tinywaffle-admin
  labels:
    app: tinywaffle
    service: admin
spec:
  selector:
    app: tinywaffle
  ports:
  - name: admin
    port: 2019
    targetPort: 2019
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: tinywaffle-metrics
  labels:
    app: tinywaffle
    service: metrics
spec:
  selector:
    app: tinywaffle
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP